skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bell_session = "56AUPR1c1Tq5AgMvAa3PASax61YYo1KTdocwW6pR7Pdx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
